name:                vformat-aeson
version:             0.1.0.1
synopsis:            Extend vformat to Aeson datatypes
github:              versioncloud/vformat-aeson
category:            Text, Format, JSON
license:             BSD3
author:              "Jorah Gao"
maintainer:          "jorah@version.cloud"
copyright:           "Copyright (c) 2020 Version Cloud"

extra-source-files:
- README.md
- ChangeLog.md

description:        Please see http://hackage.haskell.org/package/vformat-aeson

dependencies:
- aeson >= 1.2 && < 2.0
- base >= 4.9 && < 5
- bytestring >= 0.10 && < 1.0
- scientific >= 0.3 && < 1.0
- text >= 1.2 && < 2.0
- unordered-containers >= 0.2 && < 1.0
- vector >= 0.12 && < 1.0
- vformat >= 0.12 && < 1.0

library:
  source-dirs: src

tests:
  vformat-aeson-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    dependencies:
    - vformat-aeson
